### ISSUE TITLE
Incorrect Triangulation

### ISSUE THREAD

**Issue by afcsoft** [mapbox/earcut.hpp#108]
Resulting Triangulation
![Invalid Triangulation](https://user-images.githubusercontent.com/49344491/204596952-144af4ea-1203-4366-9cc1-77feac09c128.png)

Actual Polygon (rings somehow processed by the algorithm marked with arrows)
![Actual](https://user-images.githubusercontent.com/49344491/204597710-cec4d52c-2d57-471a-921a-ca1f445e0629.png)

This polygon I am trying to "earcut", contains multiple rings (some of them holes some of them not).  As can be seen from "Actual Polygon" bigger portion of the data discarded by the algorithm.  
Is this is a bug or the library does not support this types of polygons?
[Shapefile](https://github.com/mapbox/earcut.hpp/files/10115513/sample_geom.zip)

**Comment by mrgreywater** [comment]
To triangulate a shape like this with earcut you need to split it into individual polygons first. Each distinct island is a separate polygon and needs it's own call to earcut.
