### ISSUE TITLE
Builds wrong indices array for concave polygon

### ISSUE THREAD

**Issue by xahon** [mapbox/earcut.hpp#110]
I have a arrow-like polygon
![image](https://user-images.githubusercontent.com/18731681/207079938-f02fa965-e68d-418d-8566-5518b3d65409.png)

Positions are `[(-1, -1, 0), (-0.45, 0.45, 0), (1, 1, 0), (-1, 1, 0)]` in that order
![image](https://user-images.githubusercontent.com/18731681/207080309-f30f8489-534f-4ba8-97b2-84ddd8f75b0e.png)

When I pass these points (in that order) to earcut it returns me 6 indices which match these triangles (circle is starting point, red first, yellow second)
![image](https://user-images.githubusercontent.com/18731681/207081172-8a356338-da6d-4400-b1ec-1fff4f115b61.png)

Indices are `[2, 0, 1, 1, 3, 2]`

And I get this shape in the end

![image](https://user-images.githubusercontent.com/18731681/207081706-62442e98-149f-4a23-89ef-61c401bd4802.png)

**Comment by mrgreywater** [comment]
I'm unable to reproduce the issue. Using x and y of your input i get the following result:

![image](https://user-images.githubusercontent.com/2902403/207101880-ae1ee2a0-aa7c-4702-a6a3-a9c5f0219a6b.png)

**Comment by xahon** [comment]
Sorry, my bad. I was indexing into wrong array with earcut's indices
