### ISSUE TITLE
The Ear Point judgment

### ISSUE THREAD

**Issue by Coveryandcovery** [mapbox/earcut.hpp#111]
I'm comfused about the judgment condition of the ear point of the triangle area of vertex p->prev, p, and p->next must be greater than or equal to 0. In my view, it's unnecessary and even could make errors, such as the ear judgement of point b in the image.
![Uploading earcut.jpeg…]()

**Comment by Coveryandcovery** [comment]
![earcut](https://user-images.githubusercontent.com/74664996/223108316-0075f0f4-b737-4d18-a4af-1f28263f54a1.jpeg)

**Comment by mourner** [comment]
I think this check is pretty self-explanatory:

https://github.com/mapbox/earcut.hpp/blob/a5228991597521f446f4faa2464d78622378e87a/include/mapbox/earcut.hpp#L316
