### ISSUE TITLE
On node to rule them all

### ISSUE THREAD

**Issue by clement-welsch** [mapbox/earcut.hpp#114]
Hello,
First of all, thanks for sharing your code, it was really interesting to figure how Ear clipping could be implemented.
My plan was to make a triangulation on various polygons (square, infinite symbol, C shape, …).
I had an issue on a polygon "C" which has 12 indexes.
The node (11) was constantly reused to create new triangles so the harmony of the triangulation was awful.
I tweaked your code just to start from the index (1) instead of (0) for this shape specifically to solve the issue. Obviously, it is not a satisfying fix but I have reached the deadline of my project.

It might be interesting to make an evaluation of the polygon to start where it is the most efficient. Otherwise, the fact that we constantly pass ear = next->next; could explain why we always loop on the same index and kill the intention to avoid sliver triangles.
If I have more time later, I will rethink it.
Anyway, good job to you and farewell.
Before
<img width="499" alt="Screenshot 2024-07-23 115312" src="https://github.com/user-attachments/assets/50a72c59-fd41-4568-9826-ccbb1508b32d">

After
![Screenshot 2024-07-23 112226](https://github.com/user-attachments/assets/335190f1-ad56-4521-9d78-f751fba7c712)

**Comment by mrgreywater** [comment]
Both of those examples are valid triangulations. This library doesn't create a perfect delaunay triangulation, and that's ok. If you need a Delaunay triangulation, there are other libraries such as CDT.

If you can improve the output of the earcut library without sacrificing performance, you're free to create a PR, even better with some examples to show the improvement.
