### ISSUE TITLE
Stability and determinism of the earcut algorithm

### ISSUE THREAD

**Issue by Sakars360** [mapbox/earcut.hpp#116]
Hi,

I'm seeking clarification regarding the stability of the earcutting algorithm implementation, particularly in relation to cross-platform consistency, small floating-point variations, and geometric transformations (e.g., shape rotations).

By "stability," I refer to the algorithm's ability to consistently produce identical output indices (ignoring the order of triplets) when various transformations are applied to the input shape. Specifically, I have concerns about the following scenarios:
- Rotation: Does the algorithm consistently produce the same indices if the input points are rotated around a pivot?
- Translation: Will translating all vertices by the same amount yield consistent indices, assuming the translation does not introduce significant floating-point precision loss?
- Vertex Adjustment: How does the algorithm handle slight adjustments to individual vertices? Will the resulting triangulation remain the same, assuming these adjustments are minor and do not lead to an invalid configuration of triangles?
- Cross-platform consistency: Would different operating systems have any chance of returning different results?

**Comment by mourner** [comment]
I don't think there are any guarantees on consistency, and have no idea about cross-platform differences. Earcut simply triangulates a polygon as best as it can for rendering. 

Consistency after permutations was never a requirement, and honestly I'm not even sure why someone would need since it's not CDT which could have applications beyond rendering. Can you say more about your use case?

**Comment by mourner** [comment]
@Sakars360 yes, then I'd probably look into Constrained Delaynay Triangulation, since it's more stable. I'm also not sure how to handle 3D coordinates in a way that don't project to a specific plane — might need a custom solution for this, some kind of reprojection based some heuristics.

**Comment by Sakars360** [comment]
Thank you for your answer.
Currently, we disregard the vertical axis for triangulation, as it works for our use case, and as far as i can see, your ear-cutting algorithm is quite "stable" in most of our use cases. Unfortunate that you don't define any guarantees nor limitations, especially on translation and rotation as it does make it more of a black box tool.
I'm a bit saddened that this project has very limited documentation about its limitations, as 
> attempts to always produce acceptable results for practical data

is very vague.

Regardless, I appreciate you spending your time on my inquiry.
