### ISSUE TITLE
Giving credit

### ISSUE THREAD

**Issue by dmurdoch** [mapbox/earcut.hpp#118]
I'd like to include earcut.hpp in https://github.com/dmurdoch/rgl .  I'll include the copyright notice, and I'd also like to include more explicit credit, e.g. something like "The earcut code was written by the Mapbox team."  Is "Mapbox team" the right way to refer to the authors?

**Comment by mourner** [comment]
Thanks for asking! It was originally written by me in JS in https://github.com/mapbox/earcut, then ported to C++ by @kkaefer and then maintained by both Mapbox team members and those of the wider open source community. But you credit in any way you feel best.
