### ISSUE TITLE
Clean up interface

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/earcut.hpp#17]
The public interface should be:

```
template <typename Polygon, typename N = uint32_t>
std::vector<N> earcut(const Polygon&);
```

The `Coord` type should be deduced, and everything else should be hidden in a `detail` namespace.

**Comment by mrgreywater** [comment]
right now this could be easily achieved by adding 
```
    template <typename N = uint32_t, typename Polygon>
    std::vector<N> earcut(const Polygon& poly) {
        static mapbox::Earcut<N> earcut;
        earcut.operator()<Polygon>(poly);
        return earcut.indices;
    }
```
at the end of the mapbox namespace, and putting everything else in an anonymous (or mapbox::detail) namespace.
Ofcourse this would break the api and therefore would need the appropriate edits in the tests.

If this is what the maintainers of this project want, I would gladly create a pull request with the required edits.

**Comment by mrgreywater** [comment]
Any comment on it? I could also just remove the Earcut class completely, and make it look more like the earcut.js with seperate functions (in a detail/anonymous namespace). But i want to be sure that if I do the work it will actually get merged eventually.

**Comment by mourner** [comment]
I'm not a C++ developer so I'll wait for @jfirebaugh to weigh in :)

**Comment by jfirebaugh** [comment]
I think maintaining some state in an `Earcut` object makes sense, rather than passing state into every helper method. So I like you original suggesting of adding the wrapper and putting everything else in a namespace.
