### ISSUE TITLE
Doesn't build on Windows

### ISSUE THREAD

**Issue by SimonGubler** [mapbox/earcut.hpp#21]
Hi everyone

As a beginner in C++ I could not build the project. I downloaded python V.2.7.11 and ran the command

"deps\gyp\gyp.bat" earcut.gyp --depth 5

but the error message was "config.gypi not found (...) while reading includes of common.gypi..."

Could you guide me how to build the project? Alternatively, could you provide a release that is already built? I would like to use the library in a .NET project and invoke it with PInvoke.

Kind regards

Simon

**Comment by mourner** [comment]
Oh, you want to build it under Windows, right? @BergWerkGIS, any thoughts?

**Comment by BergWerkGIS** [comment]
To make this work Windows support would have to be added to `earcut.gyp` and `common.gypi`.

e.g. by default there is no `find` equivalent on Windows: https://github.com/mapbox/earcut.hpp/blob/c8701839bac55a27600beb36d81ad7a74c7dabc2/earcut.gyp#L10
Well there is a `find`, but it's output is not usable for `gyp`.

And no Windows specific definitions in [`common.gypi`](https://github.com/mapbox/earcut.hpp/blob/c8701839bac55a27600beb36d81ad7a74c7dabc2/common.gypi) at all.

**Comment by mrgreywater** [comment]
What about adding a cmake build? Cmake is easier to setup on windows, and it's more common on linux aswell.

**Comment by jfirebaugh** [comment]
Yeah, I think we're interested in moving from gyp to cmake across most of our C++ projects.

cc @kkaefer

**Comment by mrgreywater** [comment]
It should work now. @SimonGubler In case you have any more trouble building on Windows, ping me.

**Comment by SimonGubler** [comment]
Hi all

Thank you for the support, unfortunately I couldn't test it right away but now it seems to be running. Thanks a lot for the Visual Studio Project, that's great!

Kind regards

Simon
