### ISSUE TITLE
Floating Point vs Integer

### ISSUE THREAD

**Issue by mrgreywater** [mapbox/earcut.hpp#27]
earcut.hpp supports both floating point and integer as vertices type, but isn't using the fastest approach in either case. 

When using floating point data, lots of the min/max calculations are done using conditions, which slows them down, as x86/AMD64 both have branchless floating point min/max instructions which won't be used in that case. (see https://github.com/mapbox/earcut.hpp/blob/master/include/earcut.hpp#L286)

When using integer data, the code is casting to double quite frequently which slows things down aswell. Instead of casting to double, when expecting an overflow, it should cast to the next bigger integer type, for example with `boost::int_t<size>`

**Comment by mourner** [comment]
You're right about some of the lines being unoptimized — things like min/max lines were a direct JS ports, certainly they can be made faster with a C++-specific approach.

Regarding integer casts — we'd like to keep the library minimal, avoiding dependencies like boost.

If you have any particular quick fixes in mind, we'll be happy to see more PRs!

**Comment by mrgreywater** [comment]
It is already depending on boost https://github.com/mapbox/earcut.hpp/blob/master/include/earcut.hpp#L12

**Comment by mourner** [comment]
Oops, right :) I'm not knowledgeable enough to comment meaningfully here.

**Comment by jfirebaugh** [comment]
Yes, the manual min/maxing should be replaced with `std::min/max`, and it would be nice to avoid floating point calculations where it's know that integer calculations suffice.

I'd like to figure out a way to eliminate the `boost::pool` dependency (https://github.com/mapbox/earcut.hpp/pull/10#issuecomment-146342596) and have zero dependencies other than the standard library.

**Comment by mourner** [comment]
@mrgreywater is this issue still relevant?

**Comment by mrgreywater** [comment]
Yes, I think it is. Not converting from integer to floating point, and only doing integer arithmetic when working with integer vertices should increase both precision and performance. It's not strictly required though. I may look into it the next week or so, when I got more time.

**Comment by mrgreywater** [comment]
I added integer math testwise on this branch:
https://github.com/mrgreywater/earcut.hpp/tree/integer-math

To be honest; performance seems to be the same on a modern cpu (might be a different story on a embedded systems). So since this would only increase code complexity, I'd rather not push it to master, unless there's some other reason to have it (e.g numerical stability issues).

Benchmark before:
```
+----------------+--------------------+--------------------+
| Polygon        | earcut             | libtess2           |
+----------------+--------------------+--------------------+
| bad_hole       |        21948 ops/s |        14298 ops/s |
| building       |       208040 ops/s |        33326 ops/s |
| degenerate     |       579130 ops/s |        55351 ops/s |
| dude           |        17278 ops/s |         7524 ops/s |
| empty_square   |       414096 ops/s |        49824 ops/s |
| water          |          326 ops/s |           97 ops/s |
| water2         |          282 ops/s |          442 ops/s |
| water3         |         6076 ops/s |         3605 ops/s |
| water3b        |        60613 ops/s |        21924 ops/s |
| water4         |         1122 ops/s |          814 ops/s |
| water_huge     |           26 ops/s |           36 ops/s |
| water_huge2    |           12 ops/s |           48 ops/s |
+----------------+--------------------+--------------------+
```
after:
```
+----------------+--------------------+--------------------+
| Polygon        | earcut             | libtess2           |
+----------------+--------------------+--------------------+
| bad_hole       |        23908 ops/s |        13809 ops/s |
| building       |       186330 ops/s |        30338 ops/s |
| degenerate     |       564006 ops/s |        56043 ops/s |
| dude           |        17400 ops/s |         7581 ops/s |
| empty_square   |       410342 ops/s |        49425 ops/s |
| water          |          325 ops/s |           96 ops/s |
| water2         |          276 ops/s |          418 ops/s |
| water3         |         6028 ops/s |         3574 ops/s |
| water3b        |        60884 ops/s |        21765 ops/s |
| water4         |         1120 ops/s |          819 ops/s |
| water_huge     |           26 ops/s |           37 ops/s |
| water_huge2    |           12 ops/s |           46 ops/s |
+----------------+--------------------+--------------------+
```

**Comment by mrgreywater** [comment]
So on my main rig, I actually see some performance benefit i5 3570K, compiled with gcc-5.1. Still not sure if it's worth it though...
```
"bench float.exe"
+----------------+--------------------+--------------------+
| Polygon        | earcut             | libtess2           |
+----------------+--------------------+--------------------+
| bad_hole       |       158675 ops/s |        75410 ops/s |
| building       |      1634979 ops/s |       162169 ops/s |
| degenerate     |      3771630 ops/s |       237986 ops/s |
| dude           |       108349 ops/s |        40060 ops/s |
| empty_square   |      2951560 ops/s |       201882 ops/s |
| water          |         1189 ops/s |          249 ops/s |
| water2         |         1302 ops/s |         1525 ops/s |
| water3         |        39756 ops/s |        17798 ops/s |
| water3b        |       397352 ops/s |       110745 ops/s |
| water4         |         4984 ops/s |         3198 ops/s |
| water_huge     |           88 ops/s |           87 ops/s |
| water_huge2    |           42 ops/s |          122 ops/s |
+----------------+--------------------+--------------------+

"bench integer.exe"
+----------------+--------------------+--------------------+
| Polygon        | earcut             | libtess2           |
+----------------+--------------------+--------------------+
| bad_hole       |       188997 ops/s |        76098 ops/s |
| building       |      1770977 ops/s |       162322 ops/s |
| degenerate     |      4059780 ops/s |       238876 ops/s |
| dude           |       113823 ops/s |        40106 ops/s |
| empty_square   |      3170156 ops/s |       202025 ops/s |
| water          |         1442 ops/s |          249 ops/s |
| water2         |         1530 ops/s |         1544 ops/s |
| water3         |        43668 ops/s |        17928 ops/s |
| water3b        |       474675 ops/s |       110404 ops/s |
| water4         |         5880 ops/s |         3183 ops/s |
| water_huge     |          118 ops/s |           85 ops/s |
| water_huge2    |           53 ops/s |          119 ops/s |
+----------------+--------------------+--------------------+
```

**Comment by mourner** [comment]
I'm not sure, the fraction logic indeed complicates the code considerably... @jfirebaugh have an opinion?

**Comment by mrgreywater** [comment]
The thing about the fraction logic is, that theoretically it could be mostly removed. Instead one could simply do the division, and work on the integer grid while finding a hole connection (basically bresenham's line rasterization). With the tanCur/tanMin calculation, It's not that complicated and could likely be converted into some approximated atan2 angle instead.
While both of these things would work, they will also yield slightly different results than the original javascript library, and I really like the fact that they're both returning the exact same results right now.

Alternatively one could also adapt the javascript library to use integer math depending on the input, but optimization would highly depend on the used jit engine and it's type tagging.

**Comment by mrgreywater** [comment]
Closing this, as there doesn't seem to be much performance gain to be had. It's especially not worth it given the increased code complexity. There may be a use case for micro-controllers without FPU, but unless somebody requires triangulation on a device like that, this isn't worth it.
