### ISSUE TITLE
Remove boost::pool dependency

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/earcut.hpp#28]
https://github.com/mapbox/earcut.hpp/pull/10#issuecomment-146342596

Since it appears we have to dynamically allocate `Node`s, an alternative to a preallocated `std::unique_ptr<Node[]>` is a `std::list<std::array<Node, N>>` with subarrays of a fixed size. `std::list` and `std::array` are chosen so that individual `Node*` are not at risk of invalidation, which would be the case with `std::vector<Node>`.

**Comment by mrgreywater** [comment]
The number of Nodes is at least the number of input vertices, and maximum the number of output triangles*3. The number of Triangles in the output is at most [N = VB + 2VI - 2](http://www.math.utah.edu/~pa/MDS/triangulation.html), so if I'm not totally wrong, we could just allocate a vector of 6 times the length of all input vertices combined. Alternatively, I guess a good block size for a block allocator would be the length of the input vertices.

**Comment by jfirebaugh** [comment]
Great analysis! Do you have any idea what a good lower bound for typical inputs is? I'm curious whether preallocating 1 or 1.5 or 2 times the number of input vertices, and then dynamically allocating after that, would be a reasonable approach.

**Comment by mrgreywater** [comment]
I haven't actually done any statistics, but by using blocks of 1.5times the length of the input, we should not have more than 4 allocations per polygon, which sounds reasonable.
