### ISSUE TITLE
Benchmark against other tessellation libraries

### ISSUE THREAD

**Issue by kkaefer** [mapbox/earcut.hpp#3]
We should add a benchmark to see whether this is actually fast, and how it fares against other established tessellation libraries, like libtess2, and Poly2Tri.

**Comment by ljbade** [comment]
Should use randomised data or at least ensure CPU cache/branch prediction does not influence running the same test in a loop.

**Comment by mourner** [comment]
There's a benchmark against libtess (make run-bench), good enough for now.
