### ISSUE TITLE
Connection between unconnected polygons

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/earcut.hpp#36]
When testing a vector tile of mapbox-terrain with earcut.hpp, I noticed a small rendering artifact of two polygons that shouldn't be connected with an area between them:

![64-broken](https://cloud.githubusercontent.com/assets/5084263/13326372/d53a5422-dba2-11e5-8539-c5d72a49b320.png)

Expected:

![64-xray](https://cloud.githubusercontent.com/assets/5084263/13326376/db60a3c4-dba2-11e5-8bdf-ab9b120982ac.png)

This definitely could be a failure on the encoding side or the rendering side, but at the moment I don't know how to test for that. @mourner any guidance for creating a useful test case here would be appreciated. cc/ @flippmoke @springmeyer @mikemorris

**Comment by mourner** [comment]
The best test case is always the offending polygon GeoJSON coordinates, although I can settle for just the vector tile and try to find extract it myself.

**Comment by jfirebaugh** [comment]
There's a script [here](https://github.com/mapbox/earcut/commit/5f981ac1d366f35fd127768725c282f0efc3f53b) that will autoreduce a test case given a vector tile URL and layer name.

**Comment by flippmoke** [comment]
@mourner GeoJSON as vector tile coordinates or as floating point WGS84?

**Comment by mourner** [comment]
@flippmoke screen coords as encoded. I'm investigating the issue.

**Comment by flippmoke** [comment]
@mourner how to get the screen coordinates or WGS84 using node-mapnik, if you need the WGS84 coordinates correct make sure you create the tile with the proper z,x,y

```javascript
"use strict";

var fs = require('fs');
var mapnik = require('mapnik');

var data = fs.readFileSync("./this_tile_name.mvt");
var vtile = new mapnik.VectorTile(0,0,0);
vtile.setData(data);
// output as geojson
fs.writeFileSync('the_tile.geojson', vtile.toGeoJSONSync('__all__'));
// output contains tile coordinates (not geojson format)
fs.writeFileSync('the_tile.json', vtile.toJSON({decode_geometry:true}));
```

**Comment by mourner** [comment]
For the record, the tile is http://mapbox-streets.s3.amazonaws.com/00/vector-terrain-2.4.0/8/16/64.vector.pbf

@flippmoke thanks!

**Comment by mourner** [comment]
It turned out to be a bug in ring classification code. Fixed by https://github.com/mapbox/mapbox-gl-js/commit/9369d51828d89d2ab0c7c30a792a7d91ce0afaa1
