### ISSUE TITLE
Water flipped in v2 tile

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/earcut.hpp#37]
Seeing a possible data problem or rendering problem in a vector-tile v2 spec mapbox-streets tile, where the water has been flipped:

![52-now](https://cloud.githubusercontent.com/assets/5084263/13342732/0cb8a606-dc02-11e5-90c7-522c1c157a52.png)

Expected:

![52-expected](https://cloud.githubusercontent.com/assets/5084263/13342735/11aeae62-dc02-11e5-8e4b-1fff1258f73a.png)

@mourner, @flippmoke, @jfirebaugh - is there a good way to quickly determine whether it's the data or rendering that is the source of the problem?

For reference - the vector tile can be found here: http://mapbox-streets.s3.amazonaws.com/04/mapbox-streets-v71x-dev-160223/7/32/52.vector.pbf

**Comment by jakepruitt** [comment]
We're also loosing islands on `7/112/68`:

![68-now](https://cloud.githubusercontent.com/assets/5084263/13343838/c669fa22-dc0d-11e5-981b-d3fbd8827c27.png)

Expected:
![68-expected](https://cloud.githubusercontent.com/assets/5084263/13343839/c83fa50e-dc0d-11e5-9b20-7af71c39e67e.png)

Tile can be found here: http://mapbox-streets.s3.amazonaws.com/04/mapbox-streets-v71x-dev-160223/7/112/68.vector.pbf

**Comment by flippmoke** [comment]
First tile as geojson: https://gist.github.com/flippmoke/9ac6ffe0c21e1b8eaa37

**Comment by flippmoke** [comment]
Second tile geojson: https://gist.github.com/flippmoke/3b98a3154f04967b1dc6

**Comment by mourner** [comment]
It turned out to be a bug in ring classification code. Fixed by https://github.com/mapbox/mapbox-gl-js/commit/9369d51828d89d2ab0c7c30a792a7d91ce0afaa1
