### ISSUE TITLE
Document building the project in the readme

### ISSUE THREAD

**Issue by mourner** [mapbox/earcut.hpp#39]
Let's add instructions for building from #34. cc @mrgreywater

**Comment by mrgreywater** [comment]
They are already there, in the readme. Just click on "Additional build instructions for test, benchmark and visualization:"

**Comment by mourner** [comment]
@mrgreywater oh wow, I've never seen collapsible sections on GitHub before! Yeah, not very obvious, but not sure how to make it better.
