### ISSUE TITLE
Building under OS X generates a bunch of errors/warnings

### ISSUE THREAD

**Issue by mourner** [mapbox/earcut.hpp#40]
The warnings/errors I see are: https://gist.github.com/mourner/7430e008c2d036a1ad11
cc @mrgreywater

**Comment by mrgreywater** [comment]
Can you tell me which compiler and version was used? Looks like it was compiled without "-std=c++14"

**Comment by mourner** [comment]
Found the issue — the clang id on OS X (at least on my machine) is "AppleClang", while the config checks for `STREQUAL "Clang"`.
