### ISSUE TITLE
Triangle artifact

### ISSUE THREAD

**Issue by kkaefer** [mapbox/earcut.hpp#45]
Just found a triangulation artifact in our hill shading layer:

![47 20 25 north 11 20 11 east 2016-09-05 18-33-21](https://cloud.githubusercontent.com/assets/52399/18253730/706069f0-7397-11e6-8bb2-4d8a639bb865.png)

/cc @mourner

**Comment by mourner** [comment]
Thanks, will look into it.

**Comment by huhtanen** [comment]
Has there been any progress with this? There are few similar issues that we've seen that might be related to same issue.

**Comment by mourner** [comment]
Closing this as stale — there have been a ton of robustness fixes recently, e.g. #76. Please open new issues whenever you see a bad triangulation, including the offending geometry.
