### ISSUE TITLE
Small scale polygons don't work well

### ISSUE THREAD

**Issue by nevercenter** [mapbox/earcut.hpp#53]
If I try to tesselate a 24-vertex circular polygon, if the vertex data (as floats inside a custom class of mine) is numerically small (say, the bounds of the polygon are within 0.0 to 1.0) I'll often only get one or two triangles back from the tesselation function which is obviously insufficient. As I scale it up it starts to work better and better until I get a working tesselation of the full 24-vertex polygon. Is there just some tolerance value I can change in the header to make it work properly within this small range?

**Comment by mrgreywater** [comment]
Could you upload an example polygon?

**Comment by nevercenter** [comment]
Sure, here's the polygon vertices, I'll also attach as an obj and stl file:
1.000000 0.000000 0.000000
0.965926 0.000000 0.2588190
.866025 0.000000 0.500000
0.707107 0.000000 0.707107
0.500000 0.000000 0.866025
0.258819 0.000000 0.965926
-0.000000 0.000000 1.000000
-0.258819 0.000000 0.965926
-0.500000 0.000000 0.866025
-0.707107 0.000000 0.707107
-0.866025 0.000000 0.500000
-0.965926 0.000000 0.258819
-1.000000 0.000000 -0.000000
-0.965926 0.000000 -0.258819
-0.866025 0.000000 -0.500000
-0.707107 0.000000 -0.707107
-0.500000 0.000000 -0.866025
-0.258819 0.000000 -0.965926
0.000000 0.000000 -1.000000
0.258819 0.000000 -0.965926
0.500000 0.000000 -0.866025
0.707107 0.000000 -0.707107
0.866025 0.000000 -0.500000
0.965926 0.000000 -0.258819

[Small Polygon.zip](https://github.com/mapbox/earcut.hpp/files/1373942/Small.Polygon.zip)

**Comment by nevercenter** [comment]
Sure, here are the polygon vertices, I'll also attach as an obj and stl file and upload a video that shows the tesselation changing as I scale the polygon (and only getting accurate after I get to a certain absolute size):

1.000000 0.000000 0.000000
0.965926 0.000000 0.2588190
.866025 0.000000 0.500000
0.707107 0.000000 0.707107
0.500000 0.000000 0.866025
0.258819 0.000000 0.965926
-0.000000 0.000000 1.000000
-0.258819 0.000000 0.965926
-0.500000 0.000000 0.866025
-0.707107 0.000000 0.707107
-0.866025 0.000000 0.500000
-0.965926 0.000000 0.258819
-1.000000 0.000000 -0.000000
-0.965926 0.000000 -0.258819
-0.866025 0.000000 -0.500000
-0.707107 0.000000 -0.707107
-0.500000 0.000000 -0.866025
-0.258819 0.000000 -0.965926
0.000000 0.000000 -1.000000
0.258819 0.000000 -0.965926
0.500000 0.000000 -0.866025
0.707107 0.000000 -0.707107
0.866025 0.000000 -0.500000
0.965926 0.000000 -0.258819

[Small Polygon.zip](https://github.com/mapbox/earcut.hpp/files/1373956/Small.Polygon.zip)

[Scaling polygon tesselation.mov.zip](https://github.com/mapbox/earcut.hpp/files/1373965/Scaling.polygon.tesselation.mov.zip)

**Comment by nevercenter** [comment]
For the polygon in the video I had reversed the normals so the vertices were defined in reverse order than in these files, btw.

**Comment by mrgreywater** [comment]
The above polygon is triangulated as it should. You may have an issue with preprocessing or rendering.
!["triangulation"](https://puu.sh/xVmqB/d51d21de1f.png)

**Comment by nevercenter** [comment]
I wonder if it's a Mac-specific problem or something? It's definitely not a rendering problem - when I pass in the vertex data, I'll give it this polygon with 24 points and it will only give me one or two triangles back at the smaller sizes. Here's the code I'm using:

std::vector<std::vector<Point3D>> polygonWithHoles;
std::vector<Point3D> polygon;
// vSize is the polygon size, 24 in this case, and vInfo holds the polygon vertex data
for (int i = 0; i < vSize; i++)
	polygon.push_back(vInfo[i].v);
polygonWithHoles.push_back(polygon);
// definitely returns a bad triangulation, often 3 or 6 total indices
std::vector<int> indices = mapbox::earcut<int>(polygonWithHoles);

**Comment by nevercenter** [comment]
FYI I'd defined this above to use the x and z coordinates in my custom point class:

`
// for earcut.h tesselation functions
namespace mapbox {
	namespace util {
		template <>
		struct nth<0, Point3D> {
			inline static int64_t get(const Point3D t) {
				return t.pos[0];
				};
			};
		template <>
		struct nth<1, Point3D> {
			inline static int64_t get(const Point3D t) {
				return t.pos[2];
				};
			};
	} // namespace util
} // namespace mapbox
`

**Comment by mrgreywater** [comment]
> ```
> inline static int64_t get(const Point3D t) {
> 				return t.pos[0];
> 				};
> ```
you are implicitely casting your coordinates to a 64-bit integer.
