### ISSUE TITLE
Incorrect triangulation of some letters, maybe wrong usage

### ISSUE THREAD

**Issue by aadamvanko** [mapbox/earcut.hpp#57]
Hello,

I started using your library for a triangulation of vector based font. I load the font via Qt functions and generate a path for every letter. Then I try to triangulate the points and render them as triangles with OpenGL.

1. What is the correct way of specifying polygon with holes in it? What winding should I use and how does the coordinate system look (does it have reversed Y axis)? Does the library guarantee winding of output triangles and if so which one (CW, CCW, by experimenting it is CW) ? I could not find this information in the README and I think it would be very helpful. 

2. My problem is that some letters (d, e, g, q, B) are not triangulated correctly. For example letter e . Here is how I use earcut in my code. points is filled with points from the path [desmos graph](https://www.desmos.com/calculator/eccmbginaa)  might be a little bit confusing due to reversed y axis in desmos and thus the winding looks also as it was different  , the green ones are before content of points and the orange ones are points (triangle vertices) after triangulation. As you can see it removed/ignored quite a lot of points from that curve and I don' t know why. **Should I define every polygon as separate vector and that's why it is not working or what might be the issue?**

Thanks for any help :)

Code
```
std::vector<QPointF> TriangulatePolygon2(const std::vector<QPointF>& points) {
    using VertexIndexType = uint32_t;
    using Point2D = std::pair<double, double>;

    std::vector<Point2D> verticesToTransform;
    for (QPointF point : points) {
        verticesToTransform.push_back({point.x(), point.y()});
    }
    std::vector<VertexIndexType> trianglesIndices = mapbox::earcut<VertexIndexType>(std::vector<std::vector<Point2D>>{verticesToTransform});
    std::vector<QPointF> triangleVertices;
    for (size_t i = 0; i < trianglesIndices.size(); i += 3) {
        const QPointF pointI = points[trianglesIndices[i]];
        const QPointF pointI1 = points[trianglesIndices[i + 1]];
        const QPointF pointI2 = points[trianglesIndices[i + 2]];
        // reverse y axis coordinate, QT in 2D uses top down axis instead of right hand 3D coordinate system
        // correct counter clockwise order
        triangleVertices.push_back({pointI.x(), -pointI.y()});
        triangleVertices.push_back({pointI2.x(), -pointI2.y()});
        triangleVertices.push_back({pointI1.x(), -pointI1.y()});
    }

    return triangleVertices;
}
```

The order of points in the input vector. Red points are control points for bezier curves, thus the indexing.
![image](https://user-images.githubusercontent.com/25894662/36945208-0b115886-1fab-11e8-8442-201cdf1a05e6.png)

Wrong rendering picture
![image](https://user-images.githubusercontent.com/25894662/36945223-3301d47e-1fab-11e8-8325-ce1c6ede73f2.png)

Wrong rendering wireframe
![image](https://user-images.githubusercontent.com/25894662/36945229-3e34d346-1fab-11e8-82f5-de686fafb819.png)

Input points 
`(561.057617, -222.600586), (682.121094, -207.630371), (682.121094, -207.630371), (675.905200, -186.886860), (668.712988, -167.093633), (660.544458, -148.250688), (651.399609, -130.358027), (641.278442, -113.415649), (630.180957, -97.423555), (618.107153, -82.381743), (605.057031, -68.290215), (591.030591, -55.148970), (576.027832, -42.958008), (576.027832, -42.958008), (560.107334, -31.827979), (543.327676, -21.869531), (525.688857, -13.082666), (507.190879, -5.467383), (487.833740, 0.976318), (467.617441, 6.248438), (446.541982, 10.348975), (424.607363, 13.277930), (401.813584, 15.035303), (378.160645, 15.621094), (378.160645, 15.621094), (348.457786, 14.687083), (320.011123, 11.885049), (292.820657, 7.214993), (266.886387, 0.676914), (242.208313, -7.729187), (218.786436, -18.003311), (196.620754, -30.145457), (175.711270, -44.155625), (156.057981, -60.033816), (137.660889, -77.780029), (137.660889, -77.780029), (120.780344, -97.212019), (105.676699, -118.147539), (92.349954, -140.586589), (80.800107, -164.529170), (71.027161, -189.975281), (63.031113, -216.924922), (56.811965, -245.378093), (52.369717, -275.334795), (49.704368, -306.795027), (48.815918, -339.758789), (48.815918, -339.758789), (49.714131, -373.864844), (52.408770, -406.408789), (56.899834, -437.390625), (63.187324, -466.810352), (71.271240, -494.667969), (81.151582, -520.963477), (92.828350, -545.696875), (106.301543, -568.868164), (121.571162, -590.477344), (138.637207, -610.524414), (138.637207, -610.524414), (157.135186, -628.827129), (176.700605, -645.203242), (197.333467, -659.652754), (219.033770, -672.175664), (241.801514, -682.771973), (265.636699, -691.441680), (290.539326, -698.184785), (316.509395, -703.001289), (343.546904, -705.891191), (371.651855, -706.854492), (371.651855, -706.854492), (398.871611, -705.910718), (425.075996, -703.079395), (450.265010, -698.360522), (474.438652, -691.754102), (497.596924, -683.260132), (519.739824, -672.878613), (540.867354, -660.609546), (560.979512, -646.452930), (580.076299, -630.408765), (598.157715, -612.477051), (598.157715, -612.477051), (614.852759, -592.833525), (629.790430, -571.653926), (642.970728, -548.938252), (654.393652, -524.686504), (664.059204, -498.898682), (671.967383, -471.574785), (678.118188, -442.714814), (682.511621, -412.318770), (685.147681, -380.386650), (686.026367, -346.918457), (686.026367, -346.918457), (686.019858, -344.731504), (686.000332, -342.336270), (685.967788, -339.732754), (685.922227, -336.920957), (685.863647, -333.900879), (685.792051, -330.672520), (685.707437, -327.235879), (685.609805, -323.590957), (685.499155, -319.737754), (685.375488, -315.676270), (169.879395, -315.676270), (169.879395, -315.676270), (171.695347, -293.429229), (174.539688, -272.249629), (178.412417, -252.137471), (183.313535, -233.092754), (189.243042, -215.115479), (196.200938, -198.205645), (204.187222, -182.363252), (213.201895, -167.588301), (223.244956, -153.880791), (234.316406, -141.240723), (234.316406, -141.240723), (246.188437, -129.739692), (258.633242, -119.449297), (271.650820, -110.369536), (285.241172, -102.500410), (299.404297, -95.841919), (314.140195, -90.394063), (329.448867, -86.156841), (345.330312, -83.130254), (361.784531, -81.314302), (378.811523, -80.708984), (378.811523, -80.708984), (391.510171, -81.047441), (403.831309, -82.062813), (415.774937, -83.755098), (427.341055, -86.124297), (438.529663, -89.170410), (449.340762, -92.893438), (459.774351, -97.293379), (469.830430, -102.370234), (479.508999, -108.124004), (488.810059, -114.554688), (488.810059, -114.554688), (497.733608, -121.727373), (506.279648, -129.707148), (514.448179, -138.494014), (522.239199, -148.087969), (529.652710, -158.489014), (536.688711, -169.697148), (543.347202, -181.712373), (549.628184, -194.534688), (555.531655, -208.164092), (561.057617, -222.600586), (176.388184, -412.006348), (562.359375, -412.006348), (562.359375, -412.006348), (560.510879, -429.013813), (558.089609, -445.149102), (555.095566, -460.412212), (551.528750, -474.803145), (547.389160, -488.321899), (542.676797, -500.968477), (537.391660, -512.742876), (531.533750, -523.645098), (525.103066, -533.675142), (518.099609, -542.833008), (518.099609, -542.833008), (506.572544, -555.694375), (494.381582, -567.201914), (481.526724, -577.355625), (468.007969, -586.155508), (453.825317, -593.601562), (438.978770, -599.693789), (423.468325, -604.432188), (407.293984, -607.816758), (390.455747, -609.847500), (372.953613, -610.524414), (372.953613, -610.524414), (357.068914, -609.984185), (341.698408, -608.363496), (326.842097, -605.662349), (312.499980, -601.880742), (298.672058, -597.018677), (285.358330, -591.076152), (272.558796, -584.053169), (260.273457, -575.949727), (248.502312, -566.765825), (237.245361, -556.501465), (237.245361, -556.501465), (226.736921, -545.332383), (217.211309, -533.434316), (208.668523, -520.807266), (201.108564, -507.451230), (194.531433, -493.366211), (188.937129, -478.552207), (184.325652, -463.009219), (180.697002, -446.737246), (178.051179, -429.736289), (176.388184, -412.006348)`

Triangle vertices from earcut
`(675.905200, -186.886860), (660.544458, -148.250688), (668.712988, -167.093633), (660.544458, -148.250688), (641.278442, -113.415649), (651.399609, -130.358027), (641.278442, -113.415649), (618.107153, -82.381743), (630.180957, -97.423555), (618.107153, -82.381743), (591.030591, -55.148970), (605.057031, -68.290215), (560.107334, -31.827979), (525.688857, -13.082666), (543.327676, -21.869531), (525.688857, -13.082666), (487.833740, 0.976318), (507.190879, -5.467383), (487.833740, 0.976318), (446.541982, 10.348975), (467.617441, 6.248438), (446.541982, 10.348975), (401.813584, 15.035303), (424.607363, 13.277930), (348.457786, 14.687083), (292.820657, 7.214993), (320.011123, 11.885049), (292.820657, 7.214993), (242.208313, -7.729187), (266.886387, 0.676914), (242.208313, -7.729187), (196.620754, -30.145457), (218.786436, -18.003311), (196.620754, -30.145457), (156.057981, -60.033816), (175.711270, -44.155625), (120.780344, -97.212019), (92.349954, -140.586589), (105.676699, -118.147539), (92.349954, -140.586589), (71.027161, -189.975281), (80.800107, -164.529170), (71.027161, -189.975281), (56.811965, -245.378093), (63.031113, -216.924922), (56.811965, -245.378093), (49.704368, -306.795027), (52.369717, -275.334795), (49.714131, -373.864844), (56.899834, -437.390625), (52.408770, -406.408789), (56.899834, -437.390625), (71.271240, -494.667969), (63.187324, -466.810352), (71.271240, -494.667969), (92.828350, -545.696875), (81.151582, -520.963477), (92.828350, -545.696875), (121.571162, -590.477344), (106.301543, -568.868164), (157.135186, -628.827129), (197.333467, -659.652754), (176.700605, -645.203242), (197.333467, -659.652754), (241.801514, -682.771973), (219.033770, -672.175664), (241.801514, -682.771973), (290.539326, -698.184785), (265.636699, -691.441680), (290.539326, -698.184785), (343.546904, -705.891191), (316.509395, -703.001289), (398.871611, -705.910718), (450.265010, -698.360522), (425.075996, -703.079395), (450.265010, -698.360522), (497.596924, -683.260132), (474.438652, -691.754102), (497.596924, -683.260132), (540.867354, -660.609546), (519.739824, -672.878613), (540.867354, -660.609546), (580.076299, -630.408765), (560.979512, -646.452930), (614.852759, -592.833525), (642.970728, -548.938252), (629.790430, -571.653926), (642.970728, -548.938252), (664.059204, -498.898682), (654.393652, -524.686504), (664.059204, -498.898682), (678.118188, -442.714814), (671.967383, -471.574785), (678.118188, -442.714814), (685.147681, -380.386650), (682.511621, -412.318770), (686.019858, -344.731504), (685.967788, -339.732754), (686.000332, -342.336270), (685.967788, -339.732754), (685.863647, -333.900879), (685.922227, -336.920957), (685.863647, -333.900879), (685.707437, -327.235879), (685.792051, -330.672520), (685.707437, -327.235879), (685.499155, -319.737754), (685.609805, -323.590957), (675.905200, -186.886860), (641.278442, -113.415649), (660.544458, -148.250688), (641.278442, -113.415649), (591.030591, -55.148970), (618.107153, -82.381743), (560.107334, -31.827979), (487.833740, 0.976318), (525.688857, -13.082666), (487.833740, 0.976318), (401.813584, 15.035303), (446.541982, 10.348975), (348.457786, 14.687083), (242.208313, -7.729187), (292.820657, 7.214993), (242.208313, -7.729187), (156.057981, -60.033816), (196.620754, -30.145457), (120.780344, -97.212019), (71.027161, -189.975281), (92.349954, -140.586589), (71.027161, -189.975281), (49.704368, -306.795027), (56.811965, -245.378093), (49.714131, -373.864844), (71.271240, -494.667969), (56.899834, -437.390625), (71.271240, -494.667969), (121.571162, -590.477344), (92.828350, -545.696875), (157.135186, -628.827129), (241.801514, -682.771973), (197.333467, -659.652754), (241.801514, -682.771973), (343.546904, -705.891191), (290.539326, -698.184785), (398.871611, -705.910718), (497.596924, -683.260132), (450.265010, -698.360522), (497.596924, -683.260132), (580.076299, -630.408765), (540.867354, -660.609546), (614.852759, -592.833525), (664.059204, -498.898682), (642.970728, -548.938252), (664.059204, -498.898682), (685.147681, -380.386650), (678.118188, -442.714814), (686.019858, -344.731504), (685.863647, -333.900879), (685.967788, -339.732754), (685.863647, -333.900879), (685.499155, -319.737754), (685.707437, -327.235879), (675.905200, -186.886860), (591.030591, -55.148970), (641.278442, -113.415649), (560.107334, -31.827979), (401.813584, 15.035303), (487.833740, 0.976318), (348.457786, 14.687083), (156.057981, -60.033816), (242.208313, -7.729187), (120.780344, -97.212019), (49.704368, -306.795027), (71.027161, -189.975281), (49.714131, -373.864844), (121.571162, -590.477344), (71.271240, -494.667969), (157.135186, -628.827129), (343.546904, -705.891191), (241.801514, -682.771973), (398.871611, -705.910718), (580.076299, -630.408765), (497.596924, -683.260132), (614.852759, -592.833525), (685.147681, -380.386650), (664.059204, -498.898682), (686.019858, -344.731504), (685.499155, -319.737754), (685.863647, -333.900879), (686.019858, -344.731504), (685.375488, -315.676270), (685.499155, -319.737754), (614.852759, -592.833525), (686.026367, -346.918457), (685.147681, -380.386650), (686.026367, -346.918457), (685.375488, -315.676270), (686.019858, -344.731504), (682.121094, -207.630371), (591.030591, -55.148970), (675.905200, -186.886860), (591.030591, -55.148970), (560.107334, -31.827979), (576.027832, -42.958008), (560.107334, -31.827979), (378.160645, 15.621094), (401.813584, 15.035303), (378.160645, 15.621094), (156.057981, -60.033816), (348.457786, 14.687083), (156.057981, -60.033816), (120.780344, -97.212019), (137.660889, -77.780029), (120.780344, -97.212019), (48.815918, -339.758789), (49.704368, -306.795027), (48.815918, -339.758789), (121.571162, -590.477344), (49.714131, -373.864844), (121.571162, -590.477344), (157.135186, -628.827129), (138.637207, -610.524414), (157.135186, -628.827129), (371.651855, -706.854492), (343.546904, -705.891191), (371.651855, -706.854492), (580.076299, -630.408765), (398.871611, -705.910718), (580.076299, -630.408765), (614.852759, -592.833525), (598.157715, -612.477051), (614.852759, -592.833525), (685.375488, -315.676270), (686.026367, -346.918457), (682.121094, -207.630371), (560.107334, -31.827979), (591.030591, -55.148970), (560.107334, -31.827979), (156.057981, -60.033816), (378.160645, 15.621094), (156.057981, -60.033816), (48.815918, -339.758789), (120.780344, -97.212019), (48.815918, -339.758789), (157.135186, -628.827129), (121.571162, -590.477344), (157.135186, -628.827129), (580.076299, -630.408765), (371.651855, -706.854492), (580.076299, -630.408765), (685.375488, -315.676270), (614.852759, -592.833525), (156.057981, -60.033816), (157.135186, -628.827129), (48.815918, -339.758789), (580.076299, -630.408765), (560.510879, -429.013813), (562.359375, -412.006348), (561.057617, -222.600586), (560.107334, -31.827979), (682.121094, -207.630371), (580.076299, -630.408765), (558.089609, -445.149102), (560.510879, -429.013813), (176.388184, -412.006348), (560.107334, -31.827979), (561.057617, -222.600586), (580.076299, -630.408765), (555.095566, -460.412212), (558.089609, -445.149102), (176.388184, -412.006348), (156.057981, -60.033816), (560.107334, -31.827979), (580.076299, -630.408765), (551.528750, -474.803145), (555.095566, -460.412212), (176.388184, -412.006348), (157.135186, -628.827129), (156.057981, -60.033816), (580.076299, -630.408765), (547.389160, -488.321899), (551.528750, -474.803145), (178.051179, -429.736289), (157.135186, -628.827129), (176.388184, -412.006348), (580.076299, -630.408765), (542.676797, -500.968477), (547.389160, -488.321899), (180.697002, -446.737246), (157.135186, -628.827129), (178.051179, -429.736289), (580.076299, -630.408765), (537.391660, -512.742876), (542.676797, -500.968477), (184.325652, -463.009219), (157.135186, -628.827129), (180.697002, -446.737246), (580.076299, -630.408765), (531.533750, -523.645098), (537.391660, -512.742876), (188.937129, -478.552207), (157.135186, -628.827129), (184.325652, -463.009219), (580.076299, -630.408765), (525.103066, -533.675142), (531.533750, -523.645098), (194.531433, -493.366211), (157.135186, -628.827129), (188.937129, -478.552207), (580.076299, -630.408765), (518.099609, -542.833008), (525.103066, -533.675142), (201.108564, -507.451230), (157.135186, -628.827129), (194.531433, -493.366211), (580.076299, -630.408765), (506.572544, -555.694375), (518.099609, -542.833008), (208.668523, -520.807266), (157.135186, -628.827129), (201.108564, -507.451230), (580.076299, -630.408765), (494.381582, -567.201914), (506.572544, -555.694375), (217.211309, -533.434316), (157.135186, -628.827129), (208.668523, -520.807266), (580.076299, -630.408765), (481.526724, -577.355625), (494.381582, -567.201914), (226.736921, -545.332383), (157.135186, -628.827129), (217.211309, -533.434316), (580.076299, -630.408765), (468.007969, -586.155508), (481.526724, -577.355625), (237.245361, -556.501465), (157.135186, -628.827129), (226.736921, -545.332383), (580.076299, -630.408765), (453.825317, -593.601562), (468.007969, -586.155508), (248.502312, -566.765825), (157.135186, -628.827129), (237.245361, -556.501465), (580.076299, -630.408765), (438.978770, -599.693789), (453.825317, -593.601562), (260.273457, -575.949727), (157.135186, -628.827129), (248.502312, -566.765825), (580.076299, -630.408765), (423.468325, -604.432188), (438.978770, -599.693789), (272.558796, -584.053169), (157.135186, -628.827129), (260.273457, -575.949727), (580.076299, -630.408765), (407.293984, -607.816758), (423.468325, -604.432188), (285.358330, -591.076152), (157.135186, -628.827129), (272.558796, -584.053169), (580.076299, -630.408765), (390.455747, -609.847500), (407.293984, -607.816758), (298.672058, -597.018677), (157.135186, -628.827129), (285.358330, -591.076152), (157.135186, -628.827129), (390.455747, -609.847500), (580.076299, -630.408765), (312.499980, -601.880742), (157.135186, -628.827129), (298.672058, -597.018677), (157.135186, -628.827129), (372.953613, -610.524414), (390.455747, -609.847500), (326.842097, -605.662349), (157.135186, -628.827129), (312.499980, -601.880742), (157.135186, -628.827129), (357.068914, -609.984185), (372.953613, -610.524414), (341.698408, -608.363496), (157.135186, -628.827129), (326.842097, -605.662349), (157.135186, -628.827129), (341.698408, -608.363496), (357.068914, -609.984185), (562.359375, -412.006348), (685.375488, -315.676270), (580.076299, -630.408765), (561.057617, -222.600586), (562.359375, -412.006348), (176.388184, -412.006348), (562.359375, -412.006348), (169.879395, -315.676270), (685.375488, -315.676270)`

**Comment by mrgreywater** [comment]
The winding order of the input doesn't matter, earcut will handle both CW and CCW input polygons. Earcut's output is always clockwise.
As for the input of holes: Earcut takes a vector of polygon outlines. The first outline is the main sourrounding outline, subsequent outlines are for holes. As an example you can look at the fixture files, e.g. https://github.com/mapbox/earcut.hpp/blob/master/test/fixtures/water_huge.cpp

To pass your polygon, it should look kinda like this:

```
std::vector<Point> main_poly;
main_poly.push_back(...);
std::vector<Point> hole_1;
hole_1.push_back(...);
std::vector<Point> hole_2;
hole_2.push_back(...);

std::vector<std::vector<Point>> poly;
poly.push_back(main_poly);
poly.push_back(hole_1);
poly.push_back(hole_2);
```

**Comment by aadamvanko** [comment]
Hi,

The problem was as you can see in my code that I passed all polylines in one vector. Yeah, you should put info from this comment about winding and holes to the README, it will help a lot of newcomers like me :) .

Thanks
