### ISSUE TITLE
Missing triangles when tesselating concave polygons

### ISSUE THREAD

**Issue by StuntHacks** [mapbox/earcut.hpp#58]
I have a concave polygon with the following vertices:

```
0: { 20, 24 }
1: { 13, 124 }
2: { 200, 154 }
3: { 170, 24 }
4: { 130, 4 }
5: { 180, 40 }
6: { 80, 10 }
```

When trying to tesselate this polygon, I get the following indices:

```
1, 0, 6
5, 4, 3
3. 2, 1
1, 6, 5
```

This means, there is a triangle missing from the polygon. To help you understand how the polygon looks like, this is what it looks like when rendered (with the indices generated from this library): 
![image](https://user-images.githubusercontent.com/11249519/37177197-0774d370-231f-11e8-8923-85bdb33aeaff.png)

For reference, this is what it should look like:
![image](https://user-images.githubusercontent.com/11249519/37177412-a5ad2ce0-231f-11e8-98ba-523e4c667e47.png)

This is the code I used for inputting the vertices and then tesselating them:
```cpp
#include "earcut.hpp"
#include <iostream>
#include <string>

int main() {
    using Point = std::array<double, 2>;
    std::vector<std::vector<Point>> polygon;
    std::vector<Point> points;
    Point currentPoint;
    double x, y;
    std::string next;

        do {
            std::cout << "Enter the X coordinate: ";
            std::cin >> x;
            std::cout << "Enter the Y coordinate: ";
            std::cin >> y;

            currentPoint = { x, y };
            points.push_back(currentPoint);

            std::cout << "Continue? (Y/N)";
            std::cin >> next;
        } while(next != "N" && next != "n");

        polygon.push_back(points);
        std::vector<uint16_t> indices = mapbox::earcut<uint16_t>(polygon);

    return 0;
}
```

I hope you can help, your implementation is the best and fastest I have seen yet and I would love to use it!

**Comment by mrgreywater** [comment]
The polygon in question is not a simple polygon, did you mix up the order of the input polyline?
Your points look like this:
`{
    {{ 20, 24 }, { 13, 124 }, { 200, 154 }, { 170, 24 }, { 130, 4 }, { 180, 40 }, { 80, 10 }}
}`
![earcut](https://puu.sh/zDBiF/e6d501b44a.png)
![scanline](https://puu.sh/zDBk0/5ac7274cc7.png)

**Comment by StuntHacks** [comment]
Oh, yes, I just noticed I messed up a Vertex. Vertex 5 should be `{ 100, 40 }` instead of `{ 180, 40 }`.  Thanks for you help, I don't think I would have noticed that without your comment mentioning it.
