### ISSUE TITLE
Add github topics to description

### ISSUE THREAD

**Issue by mrgreywater** [mapbox/earcut.hpp#59]
Don't have the access to do it myself, so I'm opening an issue instead ;)
This might improve exposure and search results on google and other search engines.

Some suggestions, similar to earcut.js:
_triangulation
tessellation
geometry
algorithm
rendering
vector graphics
polygon
header-only
cpp
c++11_

**Comment by mourner** [comment]
Upped your permission level, try now :)

**Comment by mrgreywater** [comment]
Thank you, and done!
