### ISSUE TITLE
Port bugfixes from JS

### ISSUE THREAD

**Issue by kkaefer** [mapbox/earcut.hpp#6]
* [x] https://github.com/mapbox/earcut/issues/16: https://github.com/mapbox/earcut/commit/6547cc6da6e237ff10d4651be8843141c5cfa8cd and https://github.com/mapbox/earcut/commit/e457796c961a73f3d2bcb4f104c6d07e19708a57
  * Test is failing even after the fix
* [x] https://github.com/mapbox/earcut/issues/17: https://github.com/mapbox/earcut/commit/d708db92a57ec78d24c4bb4523636e705614dc7e
  * Test is failing even after the fix
* [x] https://github.com/mapbox/earcut/issues/29: https://github.com/mapbox/earcut/commit/44cc151500dd0bf1e9d39917092d3f1654b73421
  * Test is failing even after the fix
* [x] https://github.com/mapbox/earcut/issues/41: https://github.com/mapbox/earcut/commit/deb0bfee2245012c98f62f1ee3bb6a206b89db1e
* [x] https://github.com/mapbox/earcut/issues/45: https://github.com/mapbox/earcut/commit/65c7da544996fb479a2caa3d4188734cb22ce5d8

**Comment by mourner** [comment]
Another fix to port: https://github.com/mapbox/earcut/issues/17
Also note that mapbox/earcut#16 can be simplified to https://github.com/mapbox/earcut/commit/e457796c961a73f3d2bcb4f104c6d07e19708a57

**Comment by mourner** [comment]
One more: https://github.com/mapbox/earcut/commit/44cc151500dd0bf1e9d39917092d3f1654b73421

**Comment by jfirebaugh** [comment]
* [ ] Port test for https://github.com/mapbox/earcut/issues/16, check that it fails
* [ ] Port https://github.com/mapbox/earcut/commit/6547cc6da6e237ff10d4651be8843141c5cfa8cd and https://github.com/mapbox/earcut/commit/e457796c961a73f3d2bcb4f104c6d07e19708a57, check that test passes

**Comment by jfirebaugh** [comment]
@mourner @kkaefer See my PR and the checklist above. I probably did something dumb but the ported tests aren't passing.

**Comment by jfirebaugh** [comment]
I realized I should be using index equality comparisons rather than value comparisons. But tests are still failing.

**Comment by mourner** [comment]
@jfirebaugh actually @kkaefer mentioned that tests fail in master as well, and this started happening without code changes, likely after compiler set up change.

**Comment by mourner** [comment]
About https://github.com/mapbox/earcut/pull/14 — since the C++ port used indexed output from the start, I assume it was correct from the beginning so no need for a port, but need to confirm with @kkaefer.

**Comment by mourner** [comment]
@jfirebaugh oh disregard the test failing thing, it was about geojson-vt.

**Comment by jfirebaugh** [comment]
The fixes are now merged, however the test cases are not, because they fail. This needs investigation -- see the `port-tests` branch.

**Comment by mourner** [comment]
One more to port: https://github.com/mapbox/earcut/commit/deb0bfee2245012c98f62f1ee3bb6a206b89db1e

**Comment by mourner** [comment]
Tried porting the last one, but it's a noticeable performance hit on C++. Is it OK to diverge JS and C++ implementations around this then?
