### ISSUE TITLE
Incorrect triangulation on polygon without holes

### ISSUE THREAD

**Issue by aadamvanko** [mapbox/earcut.hpp#60]
Hi, 

I am using Earcut for the triangulation of font glyphs and now I am implementing the inner outlines. Everything works well except this polygon without holes. It makes the triangle lines run through a non polygon area. I am generating points from bezier curves with some number of steps as a parameter. The points are little more precise, because they are double and have about 10 digits after decimal point but to_string gave me this, if it is not good enough I will post the original.

I am using enclosed polylines thus first and last point in the path is the same. Is it bad to use enclosed polylines like this for Earcut?

Could it be problem with a precision or something?

Thanks for the help

![1](https://user-images.githubusercontent.com/25894662/37567177-7a7466d2-2ac3-11e8-8567-e6a801cff907.PNG)

![2](https://user-images.githubusercontent.com/25894662/37567178-7ed04bec-2ac3-11e8-8cf6-6ac18cdf9acf.PNG)

[Polyline points on desmos](https://www.desmos.com/calculator/z2tt3eezcl)

Polyline points in vector friendly format
`{53.949310, -4.918930}, {33.122849, -7.631439}, {34.627930, -26.565918}, {34.633484, -26.398453}, {34.722870, -25.560196}, {34.882935, -24.723495}, {35.124268, -23.891434}, {35.457382, -23.072128}, {35.890213, -22.279892}, {36.424698, -21.534241}, {37.049622, -20.862045}, {37.741562, -20.282684}, {38.483948, -19.798050}, {39.263855, -19.406586}, {40.065781, -19.104767}, {40.878983, -18.885117}, {41.697449, -18.738510}, {42.519165, -18.656097}, {43.348495, -18.630112}, {44.177872, -18.656158}, {44.999969, -18.739075}, {45.819931, -18.887466}, {46.636124, -19.111389}, {47.442551, -19.421555}, {48.227310, -19.827103}, {48.972717, -20.332550}, {49.656998, -20.934311}, {50.258759, -21.618591}, {50.764206, -22.363998}, {51.169754, -23.148758}, {51.479919, -23.955185}, {51.703842, -24.771378}, {51.852234, -25.591339}, {51.935150, -26.413437}, {51.961258, -27.244598}, {51.934845, -28.063873}, {51.850800, -28.878815}, {51.701035, -29.691772}, {51.476532, -30.499985}, {51.168259, -31.296600}, {50.769257, -32.069733}, {50.277069, -32.803146}, {49.691422, -33.483597}, {49.015579, -34.094940}, {48.269852, -34.615051}, {47.481140, -35.034286}, {46.668137, -35.355911}, {45.843918, -35.588501}, {45.015564, -35.742691}, {44.185364, -35.828827}, {43.348511, -35.855835}, {42.511703, -35.828873}, {41.681992, -35.743286}, {40.855240, -35.590973}, {40.034180, -35.362839}, {39.225739, -35.049896}, {38.441696, -34.645111}, {37.698456, -34.146057}, {37.014313, -33.556839}, {36.405518, -32.887741}, {35.884827, -32.153778}, {35.459015, -31.373306}, {35.127991, -30.564133}, {34.886047, -29.740250}, {34.876251, -29.689957}, {35.792099, -41.211578}, {36.424164, -40.518631}, {37.146530, -39.858246}, {37.926651, -39.269363}, {38.764633, -38.758331}, {39.652664, -38.334366}, {40.579926, -38.004333}, {41.533859, -37.771439}, {42.502319, -37.635025}, {43.478348, -37.590881}, {44.454514, -37.635071}, {45.423431, -37.771912}, {46.378113, -38.006042}, {47.306076, -38.338516}, {48.194305, -38.766357}, {49.031296, -39.282608}, {49.808731, -39.877792}, {50.525024, -40.543900}, {51.178207, -41.273483}, {51.580643, -41.820190}, {53.949310, -4.918930}`

Indexed points:
![3](https://user-images.githubusercontent.com/25894662/37567241-55233204-2ac4-11e8-948b-d28c5dab6631.PNG)

Triangulation code
```
std::vector<QPointF> TriangulatePolygon(const std::vector<Polyline>& polylines) {
    using VertexIndexType = uint32_t;
    using Point2D = std::pair<double, double>;

    std::vector<std::vector<Point2D>> polygon;
    std::vector<QPointF> points;
    for (const Polyline& polyline : polylines) {
        std::vector<Point2D> point2Dpolyline;
        for (const QPointF& point : polyline.points) {
            point2Dpolyline.push_back({point.x(), point.y()});
            points.push_back(point);
        }
        polygon.push_back(point2Dpolyline);
    }

    std::vector<VertexIndexType> trianglesIndices = mapbox::earcut<VertexIndexType>(polygon);
    std::vector<QPointF> trianglesVertices;
    for (size_t i = 0; i < trianglesIndices.size(); i += 3) {
        const QPointF pointI = points[trianglesIndices[i]];
        const QPointF pointI1 = points[trianglesIndices[i + 1]];
        const QPointF pointI2 = points[trianglesIndices[i + 2]];
        // reverse y axis coordinate, QT in 2D uses top down axis instead of right hand 3D coordinate system
        // correct counter clockwise order
        trianglesVertices.push_back({pointI.x(), -pointI.y()});
        trianglesVertices.push_back({pointI2.x(), -pointI2.y()});
        trianglesVertices.push_back({pointI1.x(), -pointI1.y()});
    }

    return trianglesVertices;
}


```

**Comment by mrgreywater** [comment]
Your example points triangulate fine with earcut.hpp. There must be some issue with your postprocessing or rendering.
![](https://puu.sh/zKlwZ/108798285a.png)

**Comment by aadamvanko** [comment]
Hello,

yes, you are right. I was using version before fix56, after downloading latest version it works like it should. Sorry for a false alarm and thanks for this awesome lib ;-) .

Regards,
Adam
