### ISSUE TITLE
Loads of compile errors

### ISSUE THREAD

**Issue by mikemaikaefer** [mapbox/earcut.hpp#61]
I'm just trying to use earcut.hpp and stumble upon a lot of compile errors. All I have done until now is including the header file at the very beginning of my application. With this I end up with these errors:

1>\earcut.hpp(26): error C2864: 'mapbox::detail::Earcut<N>::vertices' : only static const integral data members can be initialized within a class
1>          \earcut.hpp(126) : see reference to class template instantiation 'mapbox::detail::Earcut<N>' being compiled
1>\earcut.hpp(34): error C2253: 'Node' : pure specifier or abstract override specifier only allowed on virtual function
1>          \earcut.hpp(32) : see reference to class template instantiation 'mapbox::detail::Earcut<N>::Node' being compiled
1>\earcut.hpp(36): error C2253: 'Node' : pure specifier or abstract override specifier only allowed on virtual function
1>\earcut.hpp(44): error C2864: 'mapbox::detail::Earcut<N>::Node::prev' : only static const integral data members can be initialized within a class
1>\earcut.hpp(45): error C2864: 'mapbox::detail::Earcut<N>::Node::next' : only static const integral data members can be initialized within a class
1>\earcut.hpp(48): error C2864: 'mapbox::detail::Earcut<N>::Node::z' : only static const integral data members can be initialized within a class
1>\earcut.hpp(51): error C2864: 'mapbox::detail::Earcut<N>::Node::prevZ' : only static const integral data members can be initialized within a class
1>\earcut.hpp(52): error C2864: 'mapbox::detail::Earcut<N>::Node::nextZ' : only static const integral data members can be initialized within a class
1>\earcut.hpp(55): error C2864: 'mapbox::detail::Earcut<N>::Node::steiner' : only static const integral data members can be initialized within a class
1>\earcut.hpp(87): error C2864: 'mapbox::detail::Earcut<N>::inv_size' : only static const integral data members can be initialized within a class
1>\earcut.hpp(99): error C2143: syntax error : missing ',' before '...'
1>          \earcut.hpp(124) : see reference to class template instantiation 'mapbox::detail::Earcut<N>::ObjectPool<T,Alloc>' being compiled
1>\earcut.hpp(100): error C2065: 'Args' : undeclared identifier
1>\earcut.hpp(100): error C2988: unrecognizable template declaration/definition
1>\earcut.hpp(100): error C2059: syntax error : '...'
1>\earcut.hpp(110): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>\earcut.hpp(117): error C2061: syntax error : identifier 'blockSize'
1>\earcut.hpp(117): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>\earcut.hpp(117): warning C4183: 'reset': missing return type; assumed to be a member function returning 'int'
1>\earcut.hpp(118): error C2143: syntax error : missing ';' before 'private'
1>\earcut.hpp(771): error C4519: default template arguments are only allowed on a class template
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by mrgreywater** [comment]
Make sure to enable at least c++11 before you compile.

**Comment by mikemaikaefer** [comment]
So does this mean it can't be used on all (still up to date) LTS-Linux-variants which do not support C++11?

**Comment by mourner** [comment]
Yes. See the [dependencies section](https://github.com/mapbox/earcut.hpp#dependencies).

**Comment by mrgreywater** [comment]
@mikemaikaefer just because your Linux distribution doesn't come with an up-to-date c++ compiler preinstalled, doesn't mean you can't install it yourself. See https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91

**Comment by mikemaikaefer** [comment]
That's an really naive idea :-(
