### ISSUE TITLE
Non-nested polygon bug?

### ISSUE THREAD

**Issue by rpoelstra** [mapbox/earcut.hpp#62]
Hi,

I think I've found a bug in earcut.hpp. When the chains are not nested, but are disconnected outer (positively oriented) polygons, a strange triangulation is calculated.
I've added the original input and the triangulated result.
<img width="242" alt="original" src="https://user-images.githubusercontent.com/26594338/37824686-b717476c-2e8d-11e8-9e8f-b5e70e26f9f4.png">
<img width="671" alt="triangulated" src="https://user-images.githubusercontent.com/26594338/37824532-3ef563ea-2e8d-11e8-8c09-1e41c5a791d6.png">

Is it possible to fix this issue?

Thanks in advance.

Kind regards,

Remco Poelstra

**Comment by mrgreywater** [comment]
Your example data actually consists of four seperate polygons. Those need to be passed and triangulated individually by earcut.
