### ISSUE TITLE
Deprecation of std::allocator::construct

### ISSUE THREAD

**Issue by kmrbolas** [mapbox/earcut.hpp#65]
Since function std::allocator::construct is deprecated in c++17 and removed in C++20, i suggest to change the line 107 of earcut.hpp from:
alloc.construct(object, std::forward<Args>(args)...);
to:
new (static_cast<void*>(object)) T(std::forward<Args>(args)...);

**Comment by mrgreywater** [comment]
Thanks for giving notice. Resolved using `std::allocator_traits` in 71f0ca9
