### ISSUE TITLE
"simple" shape comes out triangulated incorrectly

### ISSUE THREAD

**Issue by SimonDanisch** [mapbox/earcut.hpp#70]
Hi, I'm working on integrating [EarCut with Julia](https://github.com/JuliaGeometry/EarCut.jl), and run into the following wrong triangulation:
![image](https://user-images.githubusercontent.com/1010467/53106349-22811580-3533-11e9-9e88-a33f3c535e6e.png)
(color encodes index: `purple = 0`, `yellow = max_index`)

I'd have assumed, that I'm rendering things wrong, or use the API incorrectly, but the EarCut test shape comes out fine in the same pipeline:
![image](https://user-images.githubusercontent.com/1010467/53106142-bb636100-3532-11e9-88c9-17da5a33e21c.png)

If you want to reproduce, I wrote a little c++ program with the shape embedded:
https://gist.github.com/SimonDanisch/6180a1bf2de473c9f9c152725121d329#file-shape-cc

**Comment by mrgreywater** [comment]
I agree the result could be better, but your example data is heavily self intersecting in at least two areas:
Here is the outline and internal area with scanline-fill:
![image](https://user-images.githubusercontent.com/2902403/53128035-c41c5d00-355b-11e9-85f9-91574ce747e6.png)

**Comment by SimonDanisch** [comment]
Thanks for the quick reply, that really helped narrowing down the problem!
Turns out, the colors for the indices weren't distinguishable enough to see the problem. Some arcs in the polygon were reversed -.-

![image](https://user-images.githubusercontent.com/1010467/53158751-a3d4b880-35c4-11e9-8b52-79539588fa48.png)

Best,
Simon
