### ISSUE TITLE
Optimize Travis macOS builds

### ISSUE THREAD

**Issue by mourner** [mapbox/earcut.hpp#80]
Build times for #79 on Travis:

![image](https://user-images.githubusercontent.com/25395/65188084-36afd580-da76-11e9-826a-cee9e93d3fc2.png)

The macOS builds take 5x more time, and most of that time is downloading and installing Ruby (regression after #77). Maybe we could avoid that step by ditching homebrew in favor of installing ccache some other way? @springmeyer

**Comment by springmeyer** [comment]
Yes, we can alternatively install ccache via https://github.com/mapbox/mason. I've put up a PR for this at https://github.com/mapbox/earcut.hpp/pull/81
