### ISSUE TITLE
Transfer Appveyor project to Mapbox?

### ISSUE THREAD

**Issue by mourner** [mapbox/earcut.hpp#84]
Currently Appveyor builds on this project can take hours between queueing a job and running it. Should we transfer the project to the paid [Mapbox Appveyor account](https://ci.appveyor.com/account/Mapbox/)? @mrgreywater Not sure how to do that, you have the appropriate rights currently.

**Comment by mrgreywater** [comment]
I think we might need to contact appveyor support to transfer the project over. I could delete it on my end, but that would erase all builds from the past.

**Comment by mrgreywater** [comment]
Appveyor Support kindly did the transfer. The badge in the README.md needs an update, but I don't know the current project link.

**Comment by mourner** [comment]
I updated the badge, but for some reason the AppVeyor builds stopped being triggered. See this commit for example: https://github.com/mapbox/earcut.hpp/commit/ee3637f5c762e61fa96a9cec63b265148a1dc12d Not sure what's going on — any way to fix this?

**Comment by mourner** [comment]
AppVeyor back in action!
