### ISSUE TITLE
How to clip with an outside polygon 

### ISSUE THREAD

**Issue by hanthuyen8** [mapbox/earcut.hpp#88]
Hello.
Thank you for your excellent library. But I have a few questions as follows:
- When I clip with a polygon inside the image that needs the clip, it works very well. (Image 2)
- But if I clip with a polygon outside of the image that needs the clip, it happens to be wrong as illustrated above. (Image 3)
(The area I want the clip to be green.)
(The red area is the result after the clip.)
I hope you understand what I mean, because I am not fluent in English.
Thank you for your support.

Before Clip:
![image](https://user-images.githubusercontent.com/26654880/87387591-35cfcd80-c5cd-11ea-9dbd-36cd6ec2c7b0.png)

After Clip:
Clip Inside:
![image](https://user-images.githubusercontent.com/26654880/87387606-408a6280-c5cd-11ea-9451-7d0e0fe985f3.png)
Clip Outside:
![image](https://user-images.githubusercontent.com/26654880/87387363-bc37df80-c5cc-11ea-8a77-efcb37bc709f.png)

**Comment by mourner** [comment]
Unfortunately the Earcut algorithm only supports valid polygons without self-intersections. You would have to use another library to support a case like this.
