### ISSUE TITLE
When I use Clipper to cut polygons, sometimes I get some separated polygons and some holes. How can I use earcut to process these separated polygons? 

### ISSUE THREAD

**Issue by jellychen** [mapbox/earcut.hpp#91]
When I use Clipper to cut polygons, sometimes I get some separated polygons and some holes. How can I use earcut to process these separated polygons?

**Comment by mrgreywater** [comment]
You have to invoke earcut for each individual separated polygon. If you require more specific help you can provide some polygons you get from clipper as output and I'm happy to show you how to prepare them to run earcut on them.

**Comment by jellychen** [comment]
Thank you for your reply, I seem to have found a way. I'm making an SVG library, using Clipper to do clipping, and Earcut to triangulate. But because I have to run on OpenGL ES 3.0 hardware, I need to render to textures. OpenGL ES 3.0 does not yet support multi-sampling of textures. Is there any good solution for this?

**Comment by jellychen** [comment]
@mrgreywater

**Comment by mrgreywater** [comment]
An alternative to multisampling is supersampling, basically you increase the size of the texture by a factor of 2x, 4x, scale the polygons by the same amount, render them to the texture and finally downscale the output texture back to your desired size.

**Comment by jellychen** [comment]
This will lead to too much pixel filling, and the performance will be affected

**Comment by jellychen** [comment]
I'm considering whether I can use clipper to make an edge offset, then triangulate the offset part, and then make an alpha transition in GPU shader. I don't know if this is the right direction

**Comment by mrgreywater** [comment]
I think your solution would be quite blurry, but you can try. Before you do, try to check if the '[EXT_multisampled_render_to_texture](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_multisampled_render_to_texture.txt)' extension is available and use it instead.

**Comment by jellychen** [comment]
I tried to use msaa and found that the effect is not good. It should be provided by hardware, there may be many differences.
I now use clipper to cut and triangulate through earcut, but I need anti-aliasing, so I wonder if I can add some redundant data through the vertices to interpolate, and then use the shader to determine whether the current pixel is Near the edge? Is there such a technique?
@mrgreywater
