### ISSUE TITLE
Please consider adding a version tag on commit 6d18edf0ce046023a7cb55e69c4cd9ba90e2c716 or later

### ISSUE THREAD

**Issue by gsrhodes** [mapbox/earcut.hpp#95]
The last version tag so far is v0.12.4, dated October, 2017. Currently we are using commit 6d18edf0ce046023a7cb55e69c4cd9ba90e2c716, which, at the item of my creation of this issue, is the head commit of the master branch. It would be quite useful to have a new version tag at this point or, perhaps, after the merge of the infinite loop pull request (https://github.com/mapbox/earcut.hpp/pull/90).

**Comment by mrgreywater** [comment]
@mourner Could you kindly create a new Release? I'm not sure if it should be v2.2.3 - to synchronize it the JavaScript library - or something else.

**Comment by SimonDanisch** [comment]
Bump, seems like there are quite a few important commits on master ;)

**Comment by mrgreywater** [comment]
Published the current state as `v2.2.3`.

**Comment by SimonDanisch** [comment]
Thanks :)
